# This is a basic workflow to help you get started with Actions

name: Angular Github Actions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "E2E"
  E2E:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: mayurrawte/github-angular-actions@latest
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Installing Application Dependencies
      run: npm install
    
    - name: Running E2E Tests
      run: echo "Done"
